import { Property, Agent, Lead, AgencyProfile } from "./types";

// NOTE: This file simulates a database. In production, replace the functions
// below with calls to your real backend (Postgres/Supabase/Prisma, or a
// headless CMS). Every page in this project reads through these functions,
// so swapping the implementation here is enough to go live with real data.

export const agencyProfile: AgencyProfile = {
  name: "Horizon Estates",
  tagline: "Every listing, verified before it's shown.",
  logoInitials: "HE",
  city: "Lahore",
  phone: "+92 300 1234567",
  whatsapp: "923001234567",
  email: "hello@horizonestates.example",
  address: "12 Commercial Boulevard, DHA Phase 5, Lahore",
  areasCovered: ["DHA Lahore", "Bahria Town", "Johar Town", "Gulberg", "Valencia", "Raiwind Road"],
  yearsActive: 9,
};

export const agents: Agent[] = [
  {
    id: "a1",
    name: "Bilal Ahmed",
    role: "owner",
    phone: "+92 300 1234567",
    whatsapp: "923001234567",
    email: "bilal@horizonestates.example",
    avatar: "BA",
    listingsCount: 14,
  },
  {
    id: "a2",
    name: "Sana Tariq",
    role: "agent",
    phone: "+92 321 9876543",
    whatsapp: "923219876543",
    email: "sana@horizonestates.example",
    avatar: "ST",
    listingsCount: 9,
  },
  {
    id: "a3",
    name: "Usman Raza",
    role: "agent",
    phone: "+92 333 4567890",
    whatsapp: "923334567890",
    email: "usman@horizonestates.example",
    avatar: "UR",
    listingsCount: 7,
  },
];

export const properties: Property[] = [
  {
    id: "p1",
    title: "1 Kanal Modern House, DHA Phase 6",
    purpose: "sale",
    type: "house",
    status: "active",
    price: 45000000,
    priceLabel: "4.5 Crore",
    city: "Lahore",
    area: "DHA Phase 6",
    size: 1,
    sizeUnit: "kanal",
    beds: 5,
    baths: 6,
    verified: true,
    featured: true,
    coverImage: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=1200&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=1200&auto=format&fit=crop",
    ],
    description:
      "A double-storey corner house with a modern facade, finished basement, and separate servant quarters. Recently renovated kitchen and marble flooring throughout.",
    amenities: ["Basement", "Servant Quarters", "Solar Panels", "Covered Parking", "Modern Kitchen"],
    agentId: "a1",
    views: 812,
    leads: 14,
    createdAt: "2026-06-02",
  },
  {
    id: "p2",
    title: "10 Marla House, Bahria Town",
    purpose: "rent",
    type: "house",
    status: "active",
    price: 120000,
    priceLabel: "120,000 / mo",
    city: "Lahore",
    area: "Bahria Town",
    size: 10,
    sizeUnit: "marla",
    beds: 4,
    baths: 4,
    verified: true,
    featured: true,
    coverImage: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?q=80&w=1200&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?q=80&w=1200&auto=format&fit=crop",
    ],
    description: "Well-maintained house on a wide street, close to Bahria Town commercial. Ideal for a family.",
    amenities: ["Wide Street", "Near Commercial", "Covered Parking", "Backup Generator"],
    agentId: "a2",
    views: 540,
    leads: 9,
    createdAt: "2026-06-10",
  },
  {
    id: "p3",
    title: "5 Marla Residential Plot, Valencia",
    purpose: "sale",
    type: "plot",
    status: "active",
    price: 9800000,
    priceLabel: "98 Lac",
    city: "Lahore",
    area: "Valencia",
    size: 5,
    sizeUnit: "marla",
    verified: true,
    featured: true,
    coverImage: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1200&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1200&auto=format&fit=crop"],
    description: "Corner plot on a 40ft street, possession ready, all dues clear, ideal for immediate construction.",
    amenities: ["Corner Plot", "Possession Ready", "Clear Dues"],
    agentId: "a1",
    views: 389,
    leads: 6,
    createdAt: "2026-05-22",
  },
  {
    id: "p4",
    title: "Commercial Shop, Main Boulevard Gulberg",
    purpose: "sale",
    type: "commercial",
    status: "active",
    price: 32000000,
    priceLabel: "3.2 Crore",
    city: "Lahore",
    area: "Gulberg",
    size: 600,
    sizeUnit: "sqft",
    verified: false,
    featured: false,
    coverImage: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?q=80&w=1200&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1441986300917-64674bd600d8?q=80&w=1200&auto=format&fit=crop"],
    description: "Ground floor shop on Main Boulevard with high footfall, currently vacant and ready to hand over.",
    amenities: ["Main Boulevard", "High Footfall", "Vacant Possession"],
    agentId: "a3",
    views: 271,
    leads: 4,
    createdAt: "2026-06-15",
  },
  {
    id: "p5",
    title: "Office Space, Johar Town",
    purpose: "rent",
    type: "commercial",
    status: "active",
    price: 95000,
    priceLabel: "95,000 / mo",
    city: "Lahore",
    area: "Johar Town",
    size: 1500,
    sizeUnit: "sqft",
    verified: true,
    featured: false,
    coverImage: "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1200&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1200&auto=format&fit=crop"],
    description: "Fully furnished office space with 4 cabins, a conference room, and dedicated parking for 8 cars.",
    amenities: ["Furnished", "4 Cabins", "Conference Room", "Parking for 8"],
    agentId: "a2",
    views: 198,
    leads: 3,
    createdAt: "2026-06-18",
  },
  {
    id: "p6",
    title: "2 Kanal Farmhouse, Raiwind Road",
    purpose: "sale",
    type: "house",
    status: "pending",
    price: 85000000,
    priceLabel: "8.5 Crore",
    city: "Lahore",
    area: "Raiwind Road",
    size: 2,
    sizeUnit: "kanal",
    beds: 6,
    baths: 7,
    verified: true,
    featured: true,
    coverImage: "https://images.unsplash.com/photo-1613977257363-707ba9348227?q=80&w=1200&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1613977257363-707ba9348227?q=80&w=1200&auto=format&fit=crop"],
    description: "A private farmhouse with a swimming pool, orchard, and guest wing — negotiation in progress.",
    amenities: ["Swimming Pool", "Orchard", "Guest Wing", "Servant Quarters"],
    agentId: "a1",
    views: 455,
    leads: 11,
    createdAt: "2026-05-30",
  },
  {
    id: "p7",
    title: "1 Kanal Plot, DHA Phase 9",
    purpose: "sale",
    type: "plot",
    status: "sold",
    price: 28000000,
    priceLabel: "2.8 Crore",
    city: "Lahore",
    area: "DHA Phase 9",
    size: 1,
    sizeUnit: "kanal",
    verified: true,
    featured: false,
    coverImage: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1200&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1200&auto=format&fit=crop"],
    description: "Sold within two weeks of listing — a level plot on a 50ft street in Phase 9 Prism.",
    amenities: ["50ft Street", "Level Plot"],
    agentId: "a3",
    views: 623,
    leads: 18,
    createdAt: "2026-04-11",
  },
  {
    id: "p8",
    title: "3 Bed Apartment, Gulberg Heights",
    purpose: "rent",
    type: "apartment",
    status: "active",
    price: 150000,
    priceLabel: "150,000 / mo",
    city: "Lahore",
    area: "Gulberg",
    size: 2200,
    sizeUnit: "sqft",
    beds: 3,
    baths: 3,
    verified: true,
    featured: false,
    coverImage: "https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?q=80&w=1200&auto=format&fit=crop",
    images: ["https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?q=80&w=1200&auto=format&fit=crop"],
    description: "High-floor apartment with city views, gym access, and 24/7 security in a gated building.",
    amenities: ["Gym Access", "24/7 Security", "City View", "Gated Building"],
    agentId: "a2",
    views: 334,
    leads: 7,
    createdAt: "2026-06-05",
  },
];

export const leads: Lead[] = [
  {
    id: "l1",
    propertyId: "p1",
    propertyTitle: "1 Kanal Modern House, DHA Phase 6",
    name: "Ahmed Khan",
    phone: "+92 301 1112233",
    message: "Is this still available? I'd like to see it this weekend.",
    status: "new",
    createdAt: "2026-07-17",
  },
  {
    id: "l2",
    propertyId: "p3",
    propertyTitle: "5 Marla Residential Plot, Valencia",
    name: "Farah Iqbal",
    phone: "+92 333 4445566",
    message: "Can you share the ownership documents before the visit?",
    status: "contacted",
    createdAt: "2026-07-16",
  },
  {
    id: "l3",
    propertyId: "p2",
    propertyTitle: "10 Marla House, Bahria Town",
    name: "Zeeshan Malik",
    phone: "+92 345 6677889",
    message: "Interested in a 1-year lease starting next month.",
    status: "new",
    createdAt: "2026-07-16",
  },
  {
    id: "l4",
    propertyId: "p6",
    propertyTitle: "2 Kanal Farmhouse, Raiwind Road",
    name: "Imran Sheikh",
    phone: "+92 300 9998877",
    message: "What's the final asking price after negotiation?",
    status: "closed",
    createdAt: "2026-07-10",
  },
  {
    id: "l5",
    propertyId: "p8",
    propertyTitle: "3 Bed Apartment, Gulberg Heights",
    name: "Noreen Aslam",
    phone: "+92 312 3334455",
    message: "Looking for a 2-bed instead — do you have similar options?",
    status: "new",
    createdAt: "2026-07-15",
  },
];

export function getFeaturedProperties() {
  return properties.filter((p) => p.featured);
}

export function getPropertyById(id: string) {
  return properties.find((p) => p.id === id);
}

export function getAgentById(id: string) {
  return agents.find((a) => a.id === id);
}

export function formatPrice(p: Property) {
  return `₨ ${p.priceLabel}`;
}

export const dashboardStats = {
  activeListings: properties.filter((p) => p.status === "active").length,
  totalViews: properties.reduce((sum, p) => sum + p.views, 0),
  newLeads: leads.filter((l) => l.status === "new").length,
  dealsClosedThisMonth: properties.filter((p) => p.status === "sold" || p.status === "rented").length,
};
